language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
jobs:
  include:
    - stage: 'Validation'
    - script:
        - yarn install
        - yarn validate
        - yarn build
